services:
  - type: web
    name: ims-api
    env: php
    plan: free
    buildCommand: composer install --no-interaction --optimize-autoloader --no-dev && php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - fromGroup: ims-db-secrets
