name: dukaan_app
description: Dukaan - Customer Mobile App for the Somali IMS Store

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^5.4.0
  http: ^1.1.0

  # State management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2

  # Image
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0

  # UI
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4

  # Date/time
  intl: ^0.19.0

  # Utils
  path_provider: ^2.1.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
